configuration: Release
branches:
  only:
    - master

before_build:
  - nuget restore src/AspNet.Mvc.ConfigurationExporter.sln

build:
  project: src/AspNet.Mvc.ConfigurationExporter.sln       
  verbosity: minimal
